### ISSUE TITLE
Need test case for MIAF 7.3.11.2

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#1]
Looks like there is no test case for MIAF paragraph 7.3.11.2:

> Any derived image item of the item_type value 'iden' shall not be derived from an image item of item_type value 'iden'

**Comment by rbouqueau** [comment]
I think there is:
https://github.com/gpac/ComplianceWarden/blob/master/tests/miaf/invalid-derivation-iden.asm
https://github.com/gpac/ComplianceWarden/blob/master/tests/miaf/invalid-derivation-iden.ref

**Comment by aklemets** [comment]
Agreed.
