### ISSUE TITLE
Incorrect validation of 'clap' box size

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#10]
There seems to be something wrong with the test case for paragraph 12.1.3.2 in the ISOBMFF spec. It is requiring that the size of the 'clap' box be 36 bytes instead of 40.

I don't have the latest ISOBMFF spec, but in the 5th version of the spec, the box consists of eight 32-bit fields. That is 32 bytes. Plus 8 bytes for the Box header itself, equals 40 bytes.

**Comment by rbouqueau** [comment]
You have bionic eyes! :) Thank you so much!
