### ISSUE TITLE
Incorrect validation of 'pasp' box size

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#11]
There seems to be something wrong with the test case for paragraph 12.1.3.2 in the ISOBMFF spec. It is requiring that the size of the 'pasp' box be 12 bytes instead of 16.

I don't have the latest ISOBMFF spec, but in the 5th version of the spec, the box consists of two 32-bit fields. That is 8 bytes. Plus 8 bytes for the Box header itself, equals 16 bytes.

**Comment by rbouqueau** [comment]
Fixed with #10
