### ISSUE TITLE
ISOBMFF test case 12.1.3.2 reports error for 'clap' box of HEIF image item.

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#12]
When running the ISOBMFF test on a HEIF file I get an error saying that the 'clap' box is incorrectly placed inside the 'ipco' box. Actually, this is valid according to HEIF (section 6.5.9.1 in 2nd edition of the spec.) It is also valid according to MIAF.
The test should not flag this as an error since a MIAF file is a HEIF file, which is a ISOBMFF file.

**Comment by rbouqueau** [comment]
You are right. I wanted to add a test to prevent misplaced clap/pasp boxes ; I had only looked in ISOBMFF. I have added the 'ipco' case but in the end nothing prevents another specification to allow pasp/clap at another location.

**Comment by cconcolato** [comment]
In general, in ISOBMFF, the presence of a known box in a location not explicitly allowed is a grey area. The validator should not try to check that a box is only present were it was specified.

**Comment by rbouqueau** [comment]
Should we remove the location part of the test then?

**Comment by cconcolato** [comment]
or add a warning if it's found in an unusual place?

**Comment by rbouqueau** [comment]
I've added warning (although for now they are pushed in a sink until we take a decision on 'should' and other warnings).
