### ISSUE TITLE
ISOBMFF test case 12.1.3.2 reports error for 'pasp' box of HEIF image item.

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#13]
When running the ISOBMFF test on a HEIF file I get an error saying that the 'pasp' box is incorrectly placed inside the 'ipco' box. Actually, this is valid according to HEIF (section 6.5.4.1 in 2nd edition of the spec.) It is also valid according to MIAF.
The test should not flag this as an error since a MIAF file is a HEIF file, which is a ISOBMFF file.

**Comment by rbouqueau** [comment]
This was fixed by 43459015422de65aec7c115fe0527a658df05225
