### ISSUE TITLE
False negative: multiple iref boxes when ISOBMFF § 8.11.12 requires zero or one

### ISSUE THREAD

**Issue by baumanj** [gpac/ComplianceWarden#17]
Per See ISOBMFF (ISO 14496-12:2015) § 8.11.12:
> 8.11.12 Item Reference Box
> 8.11.12.1 Definition
> Box Type: ‘iref’
> Container: Metadata box (‘meta’) Mandatory: No
> Quantity: **Zero or one**

[Here's an example](https://github.com/gpac/ComplianceWarden/files/6118762/car-good-cavif-prem.avif.zip) of a non-compliant file that gives `[isobmff] No errors` from ComplianceWarden

**Comment by rbouqueau** [comment]
Hi, maintainer here. Very happy to get guided feedback about what to implement next (this check is not yet implemented). Please keep opening issues!

**Comment by rbouqueau** [comment]
I've just updated the wasm page so that you can check online.

**Comment by baumanj** [comment]
Wow! Thanks for addressing this so fast. I'm getting some errors from the tool (on basic load, before submitting any file) at the moment:
```
Tool errors:
wasm streaming compile failed: CompileError: wasm validation error: at offset 4: failed to match magic number
falling back to ArrayBuffer instantiation
failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 4: failed to match magic number
CompileError: wasm validation error: at offset 4: failed to match magic number
```
But I imagine you'll have those sorted soon and I'll check back.

**Comment by rbouqueau** [comment]
Thanks, should be fixed.

FYI the tool is also easy to build (it is C++ only): https://github.com/gpac/ComplianceWarden/blob/master/README.md. Then just execute ```bin/cw.exe avif file_to_check```.
