### ISSUE TITLE
Need test case for MIAF 7.3.11.4.1

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#2]
I could not find a test case for MIAF paragraph 7.3.11.4.1:

> All input images of a grid image item shall use the same coding format, chroma sampling format, and the same decoder configuration 

> All input items to a grid shall have the same explicit or default colour information

> The input images of a grid image item shall be encoded such that each can be independently decoded

**Comment by rbouqueau** [comment]
This one is indeed not yet done because ```nclx``` is not present it is non-trivial to compare chroma format. This was discussed at the MPEG meeting of Oct 2019.

**Comment by rbouqueau** [comment]
I've just implemented it.
