### ISSUE TITLE
AVIF/MIAF validator should reject files that set PrimaryItem to a nonexistent item

### ISSUE THREAD

**Issue by tdaede** [gpac/ComplianceWarden#20]
The following item sets the Primary Item ID to 3, however it contains only one Item. It should be rejected.
[tiger_3layer_1res.zip](https://github.com/gpac/ComplianceWarden/files/6194850/tiger_3layer_1res.zip)

**Comment by rbouqueau** [comment]
I confirm. The rule for Section 6.2 checks it is a coded image but if it is missing then no error is raised.

**Comment by rbouqueau** [comment]
Fixed. Thanks for reporting!
