### ISSUE TITLE
Assertion failed: 0 && "obu_has_size_field shall be set"

### ISSUE THREAD

**Issue by leo-barnes** [gpac/ComplianceWarden#23]
I get the following output when trying to validate `testFiles/Apple/multilayer_examples/animals_00_multilayer.avif` from here: https://github.com/AOMediaCodec/av1-avif/pull/131

That file has construction method 0 for both items. Is it the failing tool assertion that's causing the issue?

```
Result:
Compliance Warden, version v27-master-rev0-g9ebfd86.
+--------------------------------------+
| avif validation |
+--------------------------------------+

Specification description: AVIF v1.0.0, 19 February 2019
https://aomediacodec.github.io/av1-avif/

[avif][Rule #1] Warning: construction_method > 1 not supported

Tool errors:
Assertion failed: 0 && "obu_has_size_field shall be set", at: src/spec_avif.cpp,469,parseAv1Obus
```

**Comment by rbouqueau** [comment]
Thanks for reporting. This has hopefully been fixed since v27. Since I hadn't tagged I had resubmitted but this is now done. And it works :)

**Comment by rbouqueau** [comment]
NB: there may be issues with multilayered files. Please don't hesitate to open issues if you have any doubt about what cw does.
