### ISSUE TITLE
construction_method shall be equal to 0 for MIAF image items that are coded image items.

### ISSUE THREAD

**Issue by leo-barnes** [gpac/ComplianceWarden#24]
https://gpac.github.io/ComplianceWarden-wasm/avif.html gives me MIAF errors saying that I have construction_method > 0 for coded image items for [animals_00_multilayer_lsel.avif.zip](https://github.com/gpac/ComplianceWarden/files/6384047/animals_00_multilayer_lsel.avif.zip)

This is incorrect. The file I'm testing has two grids that both use construction method 1, but all the tiles use construction method 0.

**Comment by leo-barnes** [comment]
It's also giving me the following HEIF errors:
```
Specification description: HEIF - ISO/IEC 23008-12 - 2nd Edition N18310

[heif][Rule #11] Error: 'grid' version shall be equal to 0, found 97 (itemId=2)
[heif][Rule #19] Error: Wrong arity for boxes { lsel } in parents { ipco }: expected in range [0-1], found 2
```

I've verified that the `grid` item bodies has version 0 and flags 0. Best guess is that the warden is getting confused by the file containing multiple grids.

**Comment by rbouqueau** [comment]
I can't see any error with the current version (the native one, not the wasm one). Closing.
