### ISSUE TITLE
Tests missing for MIAF 7.3.6.7 and 7.3.11.4.2 chroma restrictions

### ISSUE THREAD

**Issue by farindk** [gpac/ComplianceWarden#26]
MIAF restricts `clap` transforms and `grid` sizes to be integer multiples of the chroma resolution.
This is not checked yet. I have created two test files.

Example (non-conformant) file with 99x99 clap size with 4:2:0 chroma:
[odd-sized-heic-clap.zip](https://github.com/gpac/ComplianceWarden/files/6398327/odd-sized-heic-clap.zip)

Example (non-conformant) file with 99x99 grid size with 4:2:0 chroma:
[odd-sized-heic-grid.zip](https://github.com/gpac/ComplianceWarden/files/6398326/odd-sized-heic-grid.zip)

**Comment by rbouqueau** [comment]
Thank you for the samples. This is indeed not implemented but will be.

**Comment by rbouqueau** [comment]
This is being implemented but for AVIF only at this point.

**Comment by rbouqueau** [comment]
I've implemented it.
