### ISSUE TITLE
Missing checks for MIAF paragraph 7.3.11.4.2

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#3]
I see the test case for MIAF paragraph 7.3.11.4.2 in spec_miaf_num_pixels.cpp, but it appears to be missing a test for the following rules:

> when the images are in the 4:2:2 chroma sampling format, the horizontal tile offsets and widths, and the output width, shall be even numbers

> when the images are in the 4:2:0 chroma sampling format, both the horizontal and vertical tile offsets and widths, and the output width and height, shall be even numbers

**Comment by rbouqueau** [comment]
You are right, this hasn't been done yet. Cf my comment in #2:
> This one is indeed not yet done because ```nclx``` is not present it is non-trivial to compare chroma format. This was discussed at the MPEG meeting of Oct 2019.

**Comment by rbouqueau** [comment]
I've just implemented it.
