### ISSUE TITLE
Check the requirement "The file shall list 'avif' or 'avis' in the compatible_brands field of the FileTypeBox."

### ISSUE THREAD

**Issue by wantehchang** [gpac/ComplianceWarden#31]
Section 6 of the AVIF specification says:

> The following constraints are common to files compliant with this specification:
> - ...
> - The file shall list 'avif' or 'avis' in the compatible_brands field of the FileTypeBox.
> - ...

ComplianceWarden does not check this requirement.

Note: ISO BMFF appears to require that the major brand be repeated in the compatible_brands list, but this requirement is not specified. It is only mentioned in an obscure NOTE In Annex K.4, page 242, of the sixth edition (2020-12) of ISO BMFF (ISO/IEC 14496-12:2020):

> NOTE    This document requires that the major brand be repeated in the compatible-brands, but this requirement is relaxed in the 'profiles' parameter for compactness.

**Comment by wantehchang** [comment]
I found that this is a new requirement in the draft of the next version of the AVIF specification. In v1.0.0 of the AVIF specification, this is just a "should".

**Comment by baumanj** [comment]
See also: https://github.com/MPEGGroup/FileFormat/issues/29

**Comment by rbouqueau** [comment]
I've just checked and this is a 'shall'. The section 5 ('avio') has completely changed. Last comment from @baumanj still not addressed.

NB: I have a sample sent to me by email as a reference to this issue.

**Comment by rbouqueau** [comment]
Fixed by 9fe20573d7bdcb6959a60ed1787a2236c11bb409
