### ISSUE TITLE
Wrong error level for HDR10+ issues

### ISSUE THREAD

**Issue by cconcolato** [gpac/ComplianceWarden#43]
As reported here https://github.com/AOMediaCodec/av1-hdr10plus/pull/32/files/a50e84bfead1932b15f6890d58067788324409e7..0b180a66c5cc73537c0991e9a545da0236e9ab35#r986165816 ComplianceWarden does not report errors on invalid files (e.g. duplicate or missing metadata OBUs), instead it reports them in the "warning" section despite the use of "shall" in the rule.

**Comment by rbouqueau** [comment]
Should be fixed. Indeed errors were pushed in the warning array.
