### ISSUE TITLE
Need test case for MIAF 7.3.6.6

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#5]
I could not find a test case for MIAF paragraph 7.3.6.6:

> The pixel information property shall be associated with every image that is displayable (not hidden)

**Comment by rbouqueau** [comment]
It was discussed at MPEG last October. There is my note as a result of our discussion:
> The pixi shall be present if the image is not hidden

So this has been marked as not relevant by the consortium. Let me know if you think otherwise, we can bring the subject again.

**Comment by aklemets** [comment]
Well, it is a "shall" in the spec. Are they planning to amend the spec to say "should"? If not, I don't think the discussion at the meeting is entirely relevant... The spec would take precedence over any discussion at a MPEG member's meeting.

**Comment by rbouqueau** [comment]
You are right. The result of this discussion came back to my mind and it was a pure editorial change (coming likely in the next AMD).

Thanks again for your efforts.
