### ISSUE TITLE
Make sure that AV1 HDR10+ rules from section 2 also apply when packaged in ISOBMFF

### ISSUE THREAD

**Issue by cconcolato** [gpac/ComplianceWarden#50]
https://github.com/gpac/ComplianceWarden/blob/84b1b0979952221d29f6c5f5dccf0ebd76d8fc67/src/specs/av1_hdr10plus/av1_hdr10plus.cpp#L309

**Comment by rbouqueau** [comment]
After merging #56 there are only 3 rules remaining to cover this.
