### ISSUE TITLE
Implement support for AV1-ISOBMFF 

### ISSUE THREAD

**Issue by cconcolato** [gpac/ComplianceWarden#56]
Support for version 1.2.0 (and maybe later to 1.3.0 when published).
See https://github.com/AOMediaCodec/av1-isobmff/issues/169

**Comment by rbouqueau** [comment]
@podborski We're about to resume the work on cw. Don't forget to update [aomrules.py](https://github.com/gpac/ComplianceWarden/blob/master/scripts/aomrules.py) when you feel ready!

**Comment by rbouqueau** [comment]
Progress can be tracked [here](https://github.com/gpac/ComplianceWarden/commits/av1isobmff/).

**Comment by rbouqueau** [comment]
Fixed by #71
