### ISSUE TITLE
Rule about `ispe` coming before transform properties not picked up for this image

### ISSUE THREAD

**Issue by leo-barnes** [gpac/ComplianceWarden#59]
For some reason the rule about `ispe` coming before transform properties is not picked up for the image mentioned here:
https://github.com/strukturag/libheif/issues/784#issuecomment-1477660946
(Direct link https://github.com/bigcat88/pillow_heif/raw/master/tests/images/heif_special/guitar_cw90.hif)

I've definitely seen ComplianceWarden check and warn about this for `clap`, but from what I can see this image has `irot` before `ispe`. Am I missing something, or is this a check that's not implemented yet?

**Comment by rbouqueau** [comment]
I confirm there is an issue. An early ```break``` seems incorrect. Investigating.

**Comment by rbouqueau** [comment]
Really good catch, thanks for reporting. We even had issues in our own AV1 samples, which are derived from real life samples. That's now fixed.
