### ISSUE TITLE
MIAF spec should also test HEIF spec which should test ISO BMFF spec

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#6]
It is possible that I read the code incorrectly, but it looks like when testing the MIAF spec, it is only testing the rules that are related to MIAF. So, to fully verify MIAF compliance one would have to run the program three times: Once for MIAF, once for HEIF and once for ISO BMFF.

Maybe this is intentional, but I think it would be more convenient to have the MIAF spec handler also include all the HEIF test cases, and the HEIF test cases should include all the ISO BMFF test cases.

**Comment by rbouqueau** [comment]
Agreed. My only concern is that MIAF checks are almost complete whereas HEIF and ISOBMF still require a lot of work (looking for contributors or sponsors!).

**Comment by rbouqueau** [comment]
Fixed by 41b4e1197f81dd2fc449f9f28bbc027a214057bc
