### ISSUE TITLE
AV1 HDR10+ conformance mp4

### ISSUE THREAD

**Issue by podborski** [gpac/ComplianceWarden#62]
We noticed that some rules that should be executed on an mp4 file are currently in the `unchecked` section. 

File [sparks_libaom_4096x2160_0_888_hdr10plus.mp4](https://github.com/AOMediaCodec/av1-hdr10plus/raw/main/conformance/conformance_files/Netflix/sparks_libaom_4096x2160_0_888_hdr10plus.mp4) has the following entries in [the report](https://github.com/AOMediaCodec/av1-hdr10plus/blob/main/conformance/conformance_files/Netflix/sparks_libaom_4096x2160_0_888_hdr10plus.json):

```json
        "unchecked": [
          {
            "rule": "9",
            "id": "assert-45af0987",
            "details": "Section 2.2.2\nfor each frame with show_frame = 1 or show_existing_frame = 1, there shall be one\nand only one HDR10+ metadata OBU preceding the Frame Header OBU for this frame and\nlocated after the last OBU of the previous frame (if any) or after the\nSequence Header OBU (if any) or after the start of the temporal unit"
          },
          {
            "rule": "10",
            "id": "assert-a575dc54",
            "details": "Section 2.2.2\nHDR10+ Metadata OBUs are not provided when show_frame = 0"
          },
...
          {
            "rule": "12",
            "id": "assert-aa071f33",
            "details": "Section 3.1\nFor formats that use the AV1CodecConfigurationRecord when storing\n[AV1] bitstreams (e.g. ISOBMFF and MPEG-2 TS), HDR10+ Metadata OBUs\nshall not be present in the configOBUs field of\nthe AV1CodecConfigurationRecord"
          },
          {
            "rule": "13",
            "id": "assert-398f68cd",
            "details": "Section 3.2\nAV1 Metadata sample group defined in [AV1-ISOBMFF] shall not be used."
          },
...
        ]
      },
```

Rule 12 should fail since the HDR10+ metadata OBUs are in the `av1C`.
Rule 13 should pass since there is no such sample group.

What about rules 9 and 10? Are these not tested for an mp4?

**Comment by rbouqueau** [comment]
Hi Dimitri, this tests are not implemented with ISOBMFF. There will be some progress on AV1-ISOBMFF soon and these rules will be completed!

**Comment by rbouqueau** [comment]
Related to #50

**Comment by rbouqueau** [comment]
Since the branch was merge, I think we can close this one.
