### ISSUE TITLE
AVIF rule #15: "stts" box can be omitted since all track samples are sync

### ISSUE THREAD

**Issue by y-guyon** [gpac/ComplianceWarden#68]
Running [libavif's ChangeSettingTest.AOM](https://github.com/AOMediaCodec/libavif/blob/12e066686892df1c8201cfb0d8d6c68ad248c872/tests/gtest/avifchangesettingtest.cc#L104-L110) with `-DAVIF_ENABLE_COMPLIANCE_WARDEN=ON` gives:

> Specification description: AVIF v1.0.0, 19 February 2019
> https://aomediacodec.github.io/av1-avif/
> [avif][Rule <i>#</i>15] Warning: "stts" box can be omitted since all track samples are sync

The check was introduced in https://github.com/gpac/ComplianceWarden/commit/2c9031f470eb738c016f53c171cc0aeb97c111a3.

I am trying to understand if the issue comes from libavif or from ComplianceWarden. I could not find anything related to an optional "stts" in ISO 23008-12 (HEIF), ISO 23000-22 (MIAF), ISO 23000-19 (CMAF), [AV1-AVIF v1.0.0](https://aomediacodec.github.io/av1-avif/v1.0.0.html), [AV1-AVIF v1.1.0](https://aomediacodec.github.io/av1-avif/v1.1.0.html) nor [AV1-ISOBMFF v1.2.0](https://aomediacodec.github.io/av1-isobmff/v1.2.0.html). Section 8.6.1.2.1 of ISO 14496-12 (BMFF) says `stts` is mandatory.

Section 8.6.2.1 of ISO 14496-12 says `stss` is **not** mandatory, and "If the SyncSampleBox is not present, every sample is a sync sample." So I believe there is a typo and it should be `stss` instead of `stts` checked at https://github.com/gpac/ComplianceWarden/blob/bf096d4bb35d8da48614b80ce763e3cc56361215/src/specs/avif/avif.cpp#L831-L832

**Comment by rbouqueau** [comment]
You are right, let me fix this.

**Comment by y-guyon** [comment]
Thanks for the fast fix!
