### ISSUE TITLE
ispe required for every image item

### ISSUE THREAD

**Issue by dukesook** [gpac/ComplianceWarden#74]
The sample image [here](https://github.com/opengeospatial/developer-events/blob/master/2023/Open-Standards-Code-Sprint/publicly-releasable-sample-data/bradh/ACT2020_wgs_84_trimmed.heic) fails the ComplianceWarden because items 2 & 3 don't have an ispe associated with them. However, these items are of type 'mime' and 'uri '. They're not images so they don't have a width or height. 

This usually isn't an issue because most mime items don't have properties associated with them. However, the mime & uri items in the image above do in fact have at least 1 property associated with them. Looking in heif.cpp, the rule is only checked for items that have a property associated with them.

Is the file actually compliant? Are mime items considered to be "image items"?

**Comment by rbouqueau** [comment]
The link seems dead. Can you check it?

**Comment by dukesook** [comment]
Sorry about that, I updated the link to the correct url.

**Comment by rbouqueau** [comment]
Thanks for reporting. Should be fixed now.
