### ISSUE TITLE
Missing test case for MIAF 7.3.7 and 7.3.8

### ISSUE THREAD

**Issue by aklemets** [gpac/ComplianceWarden#9]
I don't see test cases for MIAF sections 7.3.7 and 7.3.8. I see similar tests for track-level boxes, but sections 7.3.7 and 7.3.8 deal specifically with the association of these boxes to still images:

> 7.3.7	Content light level property
> 7.3.8	Mastering display colour volume property

**Comment by rbouqueau** [comment]
There are no normative 'shall' in these sections. Do you have something specific in mind?
